server:
  port: 8080

spring:
  application:
    name: zuul-gateway-service

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3307/justmop
    username: root
    password: root

zuul:
  routes:
    hello-service:
      path: /hello-api/**
      url: http://localhost:8081/hello-service/
    bye-service:
      path: /bye-api/**
      url: http://localhost:8082/bye-service/

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka